-- Migration: Add AI analysis fields to scorecards
-- Created: 2025-01-27
-- Description: Adds fields for storing Company Intelligence AI analysis results

-- Add AI fields to scorecards table
ALTER TABLE qualifyiq_scorecards
ADD COLUMN IF NOT EXISTS ai_company_analysis JSONB DEFAULT NULL,
ADD COLUMN IF NOT EXISTS ai_suggestions JSONB DEFAULT NULL,
ADD COLUMN IF NOT EXISTS ai_confidence DECIMAL(3,2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS ai_analysis_timestamp TIMESTAMPTZ DEFAULT NULL;

-- Add ai_generated flag to lead_notes for tracking AI-generated content
ALTER TABLE qualifyiq_lead_notes
ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT FALSE;

-- Create index for efficient cache lookups on AI analysis
CREATE INDEX IF NOT EXISTS idx_scorecards_ai_analysis
ON qualifyiq_scorecards USING GIN (ai_company_analysis)
WHERE ai_company_analysis IS NOT NULL;

-- Create index for timestamp-based cache queries
CREATE INDEX IF NOT EXISTS idx_scorecards_ai_timestamp
ON qualifyiq_scorecards (ai_analysis_timestamp DESC)
WHERE ai_analysis_timestamp IS NOT NULL;

-- Add comment to document the AI fields
COMMENT ON COLUMN qualifyiq_scorecards.ai_company_analysis IS 'JSON containing Company Intelligence AI analysis results';
COMMENT ON COLUMN qualifyiq_scorecards.ai_suggestions IS 'JSON containing AI-suggested BANT scores and recommendations';
COMMENT ON COLUMN qualifyiq_scorecards.ai_confidence IS 'Confidence score (0.00-1.00) of the AI analysis';
COMMENT ON COLUMN qualifyiq_scorecards.ai_analysis_timestamp IS 'Timestamp when the AI analysis was performed';
COMMENT ON COLUMN qualifyiq_lead_notes.ai_generated IS 'Whether this note was generated by AI (e.g., follow-up emails)';
